# Tạo và lập chỉ mục tensor


In [1]:
# Thêm thư viện

import numpy as np
import torch

In [2]:
torch.__version__

'2.2.1+cpu'

## 1. Các kiểu tensor và chuyển đổi
### 1.1. Tạo tensor

In [3]:
# Sử dụng list
t1 = torch.tensor([1, 2, 3])
t1

tensor([1, 2, 3])

In [4]:
# Sử dụng tuple
torch.tensor((1, 2,3 ))

tensor([1, 2, 3])

In [5]:
# Chỉ định kiểu dữ liệu cho tensor
a = np.array((1, 2,3)) # int32
t2 = torch.tensor(a)
t2

tensor([1, 2, 3], dtype=torch.int32)

In [6]:
a.dtype, t1.dtype, t2.dtype

(dtype('int32'), torch.int64, torch.int32)

In [7]:
# Kiểu float

np.array([1.1, 1.2]).dtype, torch.tensor([1.1, 1.2]).dtype, torch.tensor((np.array([1.1, 1.2]))).dtype

(dtype('float64'), torch.float32, torch.float64)

In [8]:
# Kiểu boolean
t3 = torch.tensor([True, False])
t3, t3.dtype

(tensor([ True, False]), torch.bool)

In [9]:
# Kiểu complex (số phức)
t4 = torch.tensor([1+2j, 2+1j])
t4, t4.dtype

(tensor([1.+2.j, 2.+1.j]), torch.complex64)

In [10]:
# Chỉ định kiểu dữ liệu cho tensor
torch.tensor([2, 4, 6], dtype=torch.float32)

tensor([2., 4., 6.])

In [11]:
t5 = torch.tensor([2, 1.1]) # tự xác định
t5, t5.dtype

(tensor([2.0000, 1.1000]), torch.float32)

In [12]:
t6 = torch.tensor([3, True, 3.14])
t6, t6.dtype

(tensor([3.0000, 1.0000, 3.1400]), torch.float32)

In [13]:
# thay đổi kiểu tensor mà không làm thay đổi kiểu tensor ban đầu
# tạo ra các tensor mới
t1, t1.double(), t1.short(), t1

(tensor([1, 2, 3]),
 tensor([1., 2., 3.], dtype=torch.float64),
 tensor([1, 2, 3], dtype=torch.int16),
 tensor([1, 2, 3]))

In [18]:
t1 = t1.float() # gán lại kiểu dữ liệu
t1.dtype

torch.float32

## 2. Kích thước và biến đổi tensor
### 2.1. Kích thước và ...

In [20]:
t1

tensor([1., 2., 3.])

In [19]:
# kiểm tra kích thước, hình dạng, tổng phần tử của tensor
t1.ndim, t1.shape, t1.size()

(1, torch.Size([3]), torch.Size([3]))

In [21]:
len(t1), t1.numel() # trả về số lượng phần tử

(3, 3)

In [22]:
t7 = torch.tensor([[1, 2, 3], [5, 6, 7]])
t7

tensor([[1, 2, 3],
        [5, 6, 7]])

In [23]:
t7.ndim, t7.shape, t7.size(), t7.numel()

(2, torch.Size([2, 3]), torch.Size([2, 3]), 6)

In [24]:
# Tensor không chiều

t8 = torch.tensor(1)
t8.ndim, t8.shape, t8.numel()

(0, torch.Size([]), 1)

In [25]:
# Tensor 1 chiều
t9 = torch.tensor([1])
t8.ndim, t8.shape, t8.numel()

(0, torch.Size([]), 1)

In [30]:
# Tensor nhiều chiều

a1 = np.array([[1,2 ,3], [4, 5, 6]])
a2 = np.array([[3, 3, 4], [1, 2, 6]])
t10 = torch.tensor([a1, a2])
t10, t10.ndim, t10.shape, t10.numel()

(tensor([[[1, 2, 3],
          [4, 5, 6]],
 
         [[3, 3, 4],
          [1, 2, 6]]], dtype=torch.int32),
 3,
 torch.Size([2, 2, 3]),
 12)

### 2.2. Biến đổi tensor

In [31]:
# Làm phẳng tensor
# flatten: biến đổi tensor nhiều chiều thành mảng 1 chiều

t10, t10.flatten()

(tensor([[[1, 2, 3],
          [4, 5, 6]],
 
         [[3, 3, 4],
          [1, 2, 6]]], dtype=torch.int32),
 tensor([1, 2, 3, 4, 5, 6, 3, 3, 4, 1, 2, 6], dtype=torch.int32))

In [32]:
t8, t8.flatten(), t8.flatten().ndim

(tensor(1), tensor([1]), 1)

In [33]:
# reshpae: thay đổi dạng tensor

t11 = torch.tensor([1, 2])

In [34]:
t11, t11.reshape(2,1), t1.shape, t11.reshape(2, 1).shape, t11.ndim, t11.reshape(2, 1).ndim

(tensor([1, 2]),
 tensor([[1],
         [2]]),
 torch.Size([3]),
 torch.Size([2, 1]),
 1,
 2)

In [35]:
# Chuyển đổi sang tensor 1 chiều
t11, t11.reshape(2), t11.reshape(2, ), t11.reshape(2).ndim

(tensor([1, 2]), tensor([1, 2]), tensor([1, 2]), 1)

In [37]:
# Chuyển đổi sang tensor 2 chiều
t11, t11.reshape(2, 1), t11.reshape(2, 1).ndim

(tensor([1, 2]),
 tensor([[1],
         [2]]),
 2)

In [38]:
# Chuyển đổi sang tensor 3 chiều

t11, t11.reshape(1, 1, 2), t11.reshape(1,1,2).shape, t11.reshape(1,2,1), t11.reshape(1,2, 1).ndim

(tensor([1, 2]),
 tensor([[[1, 2]]]),
 torch.Size([1, 1, 2]),
 tensor([[[1],
          [2]]]),
 3)

In [28]:
# Chuyển tensor về mảng 1 chiều
t10.reshape(-1)

tensor([1, 2, 3, 4, 5, 6, 3, 3, 4, 1, 2, 6], dtype=torch.int32)

### 3. Các cách tạo tensor khác

In [39]:
# Tensor với các giá trị 0
torch.zeros([3, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [40]:
# Tensor với các giá trị 1
torch.ones([2, 2, 3])


tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [41]:
# Tensor dạng ma trận đơn vị
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [42]:
# Tạo tensor dạng ma trận đường chéo

t1, torch.diag(t1)

(tensor([1., 2., 3.]),
 tensor([[1., 0., 0.],
         [0., 2., 0.],
         [0., 0., 3.]]))

In [43]:
# rand: tensor có các phần tử trong [0, 1]
torch.rand([2, 2])

tensor([[0.2380, 0.7552],
        [0.8552, 0.1346]])

In [44]:
# randn: tensor có các phần tử theo phân phối chuẩn
torch.randn([3, 3])

tensor([[-1.3310,  2.5648, -1.4446],
        [ 0.2783, -1.2146, -0.9686],
        [-0.5849,  2.2631, -2.3142]])

Phân phối chuẩn:$\text{out}_{i} \sim \mathcal{N}(0, 1)$

In [45]:
# normal: theo phân phối được chỉ định `normal(mean, std, ...)`
torch.normal(2, 3, size=(2, 3))

tensor([[0.4355, 6.1270, 3.9212],
        [1.8458, 3.1176, 3.7194]])

In [46]:
# randint: lấy ngẫu nhiên trong đoạn số nguyên
torch.randint(3, 15, size=(3, 4))

tensor([[11, 10,  7,  4],
        [13, 11, 14,  8],
        [ 6, 10,  5, 10]])

In [47]:
# Tạo theo một trình tự
torch.arange(5), torch.arange(3, 15, 3)

(tensor([0, 1, 2, 3, 4]), tensor([ 3,  6,  9, 12]))

In [48]:
torch.linspace(3, 20, 5)

tensor([ 3.0000,  7.2500, 11.5000, 15.7500, 20.0000])

In [50]:
# Tạo tensor với các giá trị chưa khởi tạo vào kích thước được chỉ định
torch.empty(4, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [51]:
# Điền giá trị vào tensor có kích thước được chỉ định
torch.full((3, 3), 22)

tensor([[22, 22, 22],
        [22, 22, 22],
        [22, 22, 22]])

In [52]:
# Tạo tensor kích thước tương tự tensor chỉ định
t1, torch.full_like(t1, 5)

(tensor([1., 2., 3.]), tensor([5., 5., 5.]))

In [53]:
t1 = t1.float() # Đưa về đúng kiểu dữ liệu
t1, torch.rand_like(t1), t10, torch.randint_like(t10, 3, 22)

(tensor([1., 2., 3.]),
 tensor([0.2170, 0.0411, 0.3791]),
 tensor([[[1, 2, 3],
          [4, 5, 6]],
 
         [[3, 3, 4],
          [1, 2, 6]]], dtype=torch.int32),
 tensor([[[17, 13, 20],
          [ 3, 20,  9]],
 
         [[18, 11,  4],
          [14, 11,  6]]], dtype=torch.int32))

In [54]:
t5, torch.zeros_like(t5), t5, torch.ones_like(t5)

(tensor([2.0000, 1.1000]),
 tensor([0., 0.]),
 tensor([2.0000, 1.1000]),
 tensor([1., 1.]))

### 4. Chuyển từ tensor sang các kiểu dữ liệu khác

In [55]:
# Chuyển tensor về mảng
t1, t1.numpy(), np.array(t1)

(tensor([1., 2., 3.]),
 array([1., 2., 3.], dtype=float32),
 array([1., 2., 3.], dtype=float32))

In [56]:
# Chuyển tensor thành 1 list

t1.tolist(), list(t1)

([1.0, 2.0, 3.0], [tensor(1.), tensor(2.), tensor(3.)])

In [57]:
# Chuyển đổi tensor 0 chiều về giá trị
t8, t8.item()

(tensor(1), 1)

### 5. Tạo các bản sao
- Shallow copy là quá trình sao chép tham chiếu đến vùng nhớ của tensor gốc. Khi thực hiện shallow copy, ta tạo ra một tensor mới có cùng dữ liệu với tensor gốc, nhưng các thay đổi trong tensor mới sẽ được phản ánh trực tiếp trên tensor gốc. 

- Deep copy là quá trình sao chép một bản sao hoàn toàn mới của tensor, bao gồm cả dữ liệu và kích thước. Khi thực hiện deep copy, ta tạo ra một tensor mới, hoàn toàn độc lập với tensor gốc. Các thay đổi trong tensor mới sẽ không ảnh hưởng đến tensor gốc và ngược lại. 

In [58]:
t12 = torch.arange(3, 15, 3)
t13 = t12 # cả 2 cùng trỏ đến một đối tượng
t12, t13, t12[1]

(tensor([ 3,  6,  9, 12]), tensor([ 3,  6,  9, 12]), tensor(6))

In [59]:
t12[1] = 22
t12, t13

(tensor([ 3, 22,  9, 12]), tensor([ 3, 22,  9, 12]))

In [60]:
t13[3] = 0
t12, t13

(tensor([ 3, 22,  9,  0]), tensor([ 3, 22,  9,  0]))

In [61]:
# 
t14 = t12.clone() # t14 được trỏ đến đối tượng mới
t12, t13, t14

(tensor([ 3, 22,  9,  0]), tensor([ 3, 22,  9,  0]), tensor([ 3, 22,  9,  0]))

In [63]:
t12[0] = 99
t12, t13, t14

(tensor([99, 22,  9,  0]), tensor([99, 22,  9,  0]), tensor([ 3, 22,  9,  0]))

In [64]:
t14[2] = 15
t12, t13, t14

(tensor([99, 22,  9,  0]), tensor([99, 22,  9,  0]), tensor([ 3, 22, 15,  0]))